name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ganti dengan versi Python yang sesuai, misalnya '3.7', '3.8', '3.9', atau '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Run file splitter script
        env:
          INPUT_FILE: list.txt  # Ganti dengan nama file input yang sesuai
          LINES_PER_FILE: 10  # Ganti dengan jumlah baris per file yang Anda inginkan
        run: |
          python main.py -f $INPUT_FILE -l $LINES_PER_FILE

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload --skip-existing --non-interactive dist/*
